const ap = new APlayer({
    container: document.getElementById('player'),
    mini: false,
    autoplay: false,
    theme: '#FADFA3',
    loop: 'all',
    order: 'random',
    preload: 'auto',
    volume: 0.7,
    mutex: true,
    listFolded: false,
    listMaxHeight: "720px",
    audio: [
        {
            name: '春花彼方',
            artist: 'artist',
            cover: '../favicon.ico',
            url: '../music/春花彼方.mp3',
        },
        {
            name: '星の在り処 (星之所在)',
            artist: '初音ミク',
            cover: '../favicon.ico',
            url: '../music/星の在り処 (星之所在)_初音ミク.mp3',
        },
        {
            name: '13',
            artist: 'artist',
            cover: '../favicon.ico',
            url: '../music/13.mp3',
        },
        {
            name: '2',
            artist: 'artist',
            cover: '../favicon.ico',
            url: '../music/2.mp3',
        },
        {
            name: '4',
            artist: 'artist',
            cover: '../favicon.ico',
            url: '../music/4.mp3',
        },
        {
            name: '海和雪-02',
            artist: 'artist',
            cover: '../favicon.ico',
            url: '../music/海和雪-02.mp3',
        },
        {
            name: '海と雪のシアンブル-01',
            artist: 'artist',
            cover: '../favicon.ico',
            url: '../music/海と雪のシアンブル-01.mp3',
        },
        {
            name: '海と雪のシアンブル-02',
            artist: 'artist',
            cover: '../favicon.ico',
            url: '../music/海と雪のシアンブル-02.mp3',
        },
        {
            name: '天之空6',
            artist: 'artist',
            cover: '../favicon.ico',
            url: '../music/天之空6.mp3',
        },
        {
            name: '天之空7',
            artist: 'artist',
            cover: '../favicon.ico',
            url: '../music/天之空7.mp3',
        },
        {
            name: '未来描绘',
            artist: 'artist',
            cover: '../favicon.ico',
            url: '../music/未来描绘.ogg',
        },
        {
            name: '星尘 - 星之遗物',
            artist: 'artist',
            cover: '../favicon.ico',
            url: '../music/星尘 - 星之遗物.mp3',
        },
        {
            name: '星空TeaPartyえ',
            artist: 'artist',
            cover: '../favicon.ico',
            url: '../music/星空TeaPartyえ.mp3',
        },
        {
            name: 'be confidence full ver_',
            artist: 'artist',
            cover: '../favicon.ico',
            url: '../music/be confidence full ver_.mp3',
        },
        {
            name: 'bgm01',
            artist: 'artist',
            cover: '../favicon.ico',
            url: '../music/bgm01.mp3',
        },
        {
            name: 'bgm03',
            artist: 'artist',
            cover: '../favicon.ico',
            url: '../music/bgm03.mp3',
        },
        {
            name: 'bgm11',
            artist: 'artist',
            cover: '../favicon.ico',
            url: '../music/bgm11.mp3',
        },
        {
            name: 'bgm14',
            artist: 'artist',
            cover: '../favicon.ico',
            url: '../music/bgm14.mp3',
        },
        {
            name: 'bgm32',
            artist: 'artist',
            cover: '../favicon.ico',
            url: '../music/bgm32.mp3',
        },
        {
            name: 'bjs',
            artist: 'artist',
            cover: '../favicon.ico',
            url: '../music/bjs.mp3',
        },
        {
            name: 'eufonie1',
            artist: 'artist',
            cover: '../favicon.ico',
            url: '../music/eufonie1.mp3',
        },
        {
            name: 'eufonie2',
            artist: 'artist',
            cover: '../favicon.ico',
            url: '../music/eufonie2.mp3',
        },
        {
            name: 'eufonie3',
            artist: 'artist',
            cover: '../favicon.ico',
            url: '../music/eufonie3.mp3',
        },
        {
            name: 'eufonie4',
            artist: 'artist',
            cover: '../favicon.ico',
            url: '../music/eufonie4.mp3',
        },
        {
            name: 'LSR-02',
            artist: 'artist',
            cover: '../favicon.ico',
            url: '../music/LSR-02.mp3',
        },
        {
            name: 'LSR-03',
            artist: 'artist',
            cover: '../favicon.ico',
            url: '../music/LSR-03.mp3',
        },
        {
            name: 'LSR-09',
            artist: 'artist',
            cover: '../favicon.ico',
            url: '../music/LSR-09.mp3',
        },
        {
            name: 'LSR-10',
            artist: 'artist',
            cover: '../favicon.ico',
            url: '../music/LSR-10.mp3',
        },
        {
            name: 'MargED',
            artist: 'artist',
            cover: '../favicon.ico',
            url: '../music/MargED.mp3',
        },
        {
            name: 'MargOP',
            artist: 'artist',
            cover: '../favicon.ico',
            url: '../music/MargOP.wav',
        },
        {
            name: 'my first love',
            artist: 'artist',
            cover: '../favicon.ico',
            url: '../music/my first love.mp3',
        },
        {
            name: 'unlucky2',
            artist: 'artist',
            cover: '../favicon.ico',
            url: '../music/unlucky2.mp3',
        },
        {
            name: 'unlucky7',
            artist: 'artist',
            cover: '../favicon.ico',
            url: '../music/unlucky7.mp3',
        },
        {
            name: 'キミと歩いてゆけたなら',
            artist: 'artist',
            cover: '../favicon.ico',
            url: '../music/キミと歩いてゆけたなら.mp3',
        },
        {
            name: '暖洋流',
            artist: '诗岸',
            cover: '../favicon.ico',
            url: '../music/02 暖洋流.mp3',
        }
    ]
});